baseURL = 'https://diraven.github.io/'
title = 'diraven.github.io'
theme = 'PaperMod'
languageCode = 'uk'
DefaultContentLanguage = "uk"
mainSections = ['posts']

[params]
DateFormat = "02 January 2006"
defaultTheme = "dark"


[[menu.main]]
name = "Головна"
url = "/"
weight = -1

[[menu.main]]
name = "Укр. Гендпан Спільнота"
url = "/uhc/"
weight = 999

[[menu.main]]
name = "Ліцензія"
url = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.uk"
weight = 1000
